# Generated by Django 3.1.3 on 2020-11-28 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('led_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='led',
            options={'ordering': ['-active_on']},
        ),
        migrations.AddField(
            model_name='led',
            name='active_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
